# Generated by Django 5.2.3 on 2025-06-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('H', 'High 🔥'), ('M', 'Medium ⭐'), ('L', 'Low ✅')], default='M', max_length=1),
        ),
    ]
